version: '3'

services:
  o-zero:
    build: ./o-zero
    volumes:
      - ./o-zero:/usr/src/app
    ports:
      - 5001:80

  front-end:
    image: php:apache
    volumes:
      - ./front-end:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - o-zero
